### PR TITLE
Store the disposable's finalizers in a station-variable before modifying

### LINKED ISSUE #4: Weird error with the DisposableListener
```
string(5) "thonk"
[13:52:45.152] [Server thread/CRITICAL]: [Core] ErrorException: "Indirect modification of overloaded element of SplObjectStorage has no effect" (EXCEPTION) in "/Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/DisposableListener" at line 64
--- Stack trace ---
  #0 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/DisposableListener(64): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 8, string[77] Indirect modification of overloaded element of SplObjectStorage has no effect, string[116] /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/, integer 64)
  #1 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/EventAwaiter(43): SOFe\AwaitStd\DisposableListener->addFinalizer(object pocketmine\player\Player#97484, object Closure#93979)
  #2 (): SOFe\AwaitStd\EventAwaiter->await(string[39] pocketmine\event\player\PlayerChatEvent, object Closure#93954, false, integer 3, false, array[1])
  #3 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(259): Generator->send(object Closure#94009)
  #4 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(215): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await->SOFe\AwaitStd\libs\SOFe\AwaitGenerator\{closure}()
  #5 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(119): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await->wakeup(object Closure#93987)
  #6 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(184): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await::g2c(object Generator#93974, object Closure#94004, object Closure#93998)
  #7 (): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await::race(array[2])
  #8 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(259): Generator->send(object Closure#93998)
  #9 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(215): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await->SOFe\AwaitStd\libs\SOFe\AwaitGenerator\{closure}()
  #10 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(119): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await->wakeup(object Closure#94001)
  #11 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(352): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await::g2c(object Generator#93990, array[2], array[2])
  #12 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(119): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await->wakeup(array[2])
  #13 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/await-std_dev-14/src/SOFe/AwaitStd/libs/SOFe/AwaitGenerator/Await(92): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await::g2c(object Generator#93992, NULL , object Closure#93981)
  #14 plugins/DemeterCore/src/DemeterCraftFactions/Core/commands/default/nick/NickCommand(65): SOFe\AwaitStd\libs\SOFe\AwaitGenerator\Await::f2c(object Closure#93975, NULL , object Closure#93981)
  #15 plugins/DemeterCore/src/DemeterCraftFactions/Core/commands/CoreBaseCommand(27): DemeterCraftFactions\Core\commands\default\nick\NickCommand->runInGame(object pocketmine\player\Player#97484, string[4] nick, array[0])
  #16 /Users/Eurus/Documents/Development/PocketMine-MP/4/virions/Commando_dev-43.phar/src/CortexPE/Commando/BaseCommand(143): DemeterCraftFactions\Core\commands\CoreBaseCommand->onRun(object pocketmine\player\Player#97484, string[4] nick, array[0])
  #17 pmsrc/src/command/SimpleCommandMap(220): CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#97484, string[4] nick, array[0])
  #18 pmsrc/src/Server(1394): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#97484, string[4] nick)
  #19 pmsrc/src/player/Player(1337): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#97484, string[4] nick)
  #20 plugins/FakePlayer_dev-41.phar/src/muqsit/fakeplayer/FakePlayerCommand(64): pocketmine\player\Player->chat(string[5] /nick)
  #21 pmsrc/src/command/SimpleCommandMap(220): muqsit\fakeplayer\FakePlayerCommand->execute(object pocketmine\console\ConsoleCommandSender#23659, string[2] fp, array[3])
  #22 pmsrc/src/Server(1394): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#23659, string[15] fp b chat /nick)
  #23 pmsrc/src/Server(1028): pocketmine\Server->dispatchCommand(object pocketmine\console\ConsoleCommandSender#23659, string[15] fp b chat /nick)
  #24 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()
  #25 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #26 pmsrc/src/Server(1645): pocketmine\snooze\SleeperHandler->sleepUntil(double 1639144365.1587)
  #27 pmsrc/src/Server(1034): pocketmine\Server->tickProcessor()
  #28 pmsrc/src/PocketMine(301): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[51] /Users/Eurus/Documents/Development/PocketMine-MP/4/, string[59] /Users/Eurus/Documents/Development/PocketMine-MP/4/plugins/)
  #29 pmsrc/src/PocketMine(324): pocketmine\server()
  #30 pmsrc(11): require(string[99] phar:///Users/Eurus/Documents/Development/PocketMine-MP/4/sdk/PocketMine-MP.phar)
--- End of exception information ---
```
# Code
```php
Await::f2c(function () use ($player, $s) {
    var_dump("thonk");
    while (true) {
        $event = yield Await::race([
            Core::getInstance()->getStd()->awaitEvent(PlayerChatEvent::class, fn(PlayerChatEvent $event) : bool => $event->getPlayer() === $player, false, EventPriority::NORMAL, false, $player),
            Core::getInstance()->getStd()->awaitEvent(PlayerMoveEvent::class, fn(PlayerMoveEvent $event) : bool => $event->getPlayer() === $player, false, EventPriority::MONITOR, false, $player)
        ]);
    var_dump("dakjfas");
```

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**
- Trying to fix #4

### CODE REVIEW

**Comment by Endermanbugzjfc** [comment]
omg did poggit finally build this commit

2021 => 2022

File: src/SOFe/AwaitStd/DisposableListener.php [hunk 1]
```diff
@@ -61,7 +61,9 @@ public function addFinalizer(object $disposable, Closure $closure) : void {
 		if(!$this->finalizers->contains($disposable)) {
 			$this->finalizers->attach($disposable, []);
 		}
-		$this->finalizers[$disposable][] = $closure;
+		$finalizersOfDisposable = $this->finalizers[$disposable] ?? [];
```
Comment (SOF3) [inline src/SOFe/AwaitStd/DisposableListener.php:65]:
```suggestion

		$finalizersOfDisposable = $this->finalizers[$disposable] ?? [];
```

**Review by SOF3 — CHANGES_REQUESTED** [review]

**Review by SOF3 — APPROVED** [review]
